site_name: 'micro:bit runtime'
repo_url: https://github.com/lancaster-university/microbit-dal/
pages:
    - General:
        - Introduction: 'index.md'
        - Online Development: 'online-toolchains.md'
        - Offline Development: 'installing-yotta.md'
        - Concepts: 'concepts.md'
        - The device: 'device.md'
    - uBit:
        - MicroBit: 'ubit.md'
        - i2c: 'ubit/i2c.md'
        - storage: 'ubit/storage.md'
        - serial: 'ubit/serial.md'
        - messageBus: 'ubit/messageBus.md'
        - buttons: 'ubit/button.md'
        - display: 'ubit/display.md'
        - accelerometer: 'ubit/accelerometer.md'
        - compass: 'ubit/compass.md'
        - thermometer: 'ubit/thermometer.md'
        - io: 'ubit/io.md'
        - ble: 'ubit/ble.md'
        - bleManager: 'ubit/blemanager.md'
        - radio: 'ubit/radio.md'
    - Data Types:
        - MicroBitImage: "data-types/image.md"
        - MicroBitEvent: "data-types/event.md"
        - ManagedString: "data-types/string.md"
        - PacketBuffer: "data-types/packetbuffer.md"
    - BLE:
        - Profile: "ble/profile.md"
        - AccelerometerService: "ble/accelerometer-service.md"
        - ButtonService: "ble/button-service.md"
        - DFUService: "ble/dfu-service.md"
        - EventService: "ble/event-service.md"
        - IOPinService: "ble/iopin-service.md"
        - LEDService: "ble/led-service.md"
        - MagnetometerService: "ble/magnetometer-service.md"
        - TemperatureService: "ble/temperature-service.md"
    - Extras:
        - MicroBitLightSensor: "extras/light-sensing.md"
#--------------HIDDEN PAGES BEGIN
#unfortunately this is required, otherwise mkdocs doesn't build pages not linked by nav.
    - _blemanager: "ubit/blemanager.md"
    - _buttonAB: 'ubit/multibutton.md'
    - _radioevent: 'ubit/radioevent.md'
    - _radiodatagram: 'ubit/radiodatagram.md'
#--------------HIDDEN PAGES END
markdown_extensions:
    - toc:
        permalink: True
    - admonition:
extra_css:
    - css/extra.css
extra:
    logo_url: './img/logo[whiteruntime].png'
    logo_author: 'Aluna Everitt (@AlunaEveritt on Twitter)'
theme_dir: 'runtime-theme'
